Workflow triggers only manually

diff --git a/.github/workflows/appsmithctl.yml b/.github/workflows/appsmithctl.yml
--- a/.github/workflows/appsmithctl.yml
+++ b/.github/workflows/appsmithctl.yml
@@ -3,20 +3,7 @@ name: Build Appsmithctl CLI util Workflow
 
 on:
   # This line enables manual triggering of this workflow.
-  workflow_dispatch:
-  workflow_call:
-    inputs:
-      pr:
-        description: "This is the PR number in case the workflow is being called in a pull request"
-        required: false
-        type: number
-
-  pull_request:
-    branches: [release, master]
-    paths:
-      - "deploy/docker/utils/**"
-
-# Change the working directory for all the jobs in this workflow
+  workflow_dispatch: {}
 defaults:
   run:
     working-directory: deploy/docker/utils/
@@ -37,67 +24,67 @@ jobs:
       # the code before doing anything else.
 
       # Check out merge commit with the base branch in case this workflow is invoked via pull request
-      - name: Checkout the merged commit from PR and base branch
-        if: inputs.pr != 0
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-          ref: refs/pull/${{ inputs.pr }}/merge
+    - name: Checkout the merged commit from PR and base branch
+      if: inputs.pr != 0
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+        ref: refs/pull/${{ inputs.pr }}/merge
 
       # Checkout the code in the current branch in case the workflow is called because of a branch push event
-      - name: Checkout the head commit of the branch
-        if: inputs.pr == 0
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+    - name: Checkout the head commit of the branch
+      if: inputs.pr == 0
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
 
-      - name: Figure out the PR number
-        run: echo ${{ inputs.pr }}
+    - name: Figure out the PR number
+      run: echo ${{ inputs.pr }}
 
-      - name: Print the Github event
-        run: echo ${{ github.event_name }}
+    - name: Print the Github event
+      run: echo ${{ github.event_name }}
 
       # In case this is second attempt try restoring status of the prior attempt from cache
-      - name: Restore the previous run result
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/appsmithctl_run_result
-          key: ${{ github.run_id }}-${{ github.job }}-appsmithctl-util
+    - name: Restore the previous run result
+      uses: actions/cache@v3
+      with:
+        path: |
+          ~/appsmithctl_run_result
+        key: ${{ github.run_id }}-${{ github.job }}-appsmithctl-util
 
       # Fetch prior run result
-      - name: Get the previous run result
-        id: appsmithctl_run_result
-        run: cat ~/appsmithctl_run_result 2>/dev/null || echo 'default'
+    - name: Get the previous run result
+      id: appsmithctl_run_result
+      run: cat ~/appsmithctl_run_result 2>/dev/null || echo 'default'
 
       # In case of prior failure run the job
-      - if: steps.appsmithctl_run_result.outputs.appsmithctl_run_result != 'success'
-        run: echo "I'm alive!" && exit 0
+    - if: steps.appsmithctl_run_result.outputs.appsmithctl_run_result != 'success'
+      run: echo "I'm alive!" && exit 0
 
-      - name: Use Node.js 16.14.0
-        if: steps.appsmithctl_run_result.outputs.appsmithctl_run_result != 'success'
-        uses: actions/setup-node@v3
-        with:
-          node-version: "16.14.0"
+    - name: Use Node.js 16.14.0
+      if: steps.appsmithctl_run_result.outputs.appsmithctl_run_result != 'success'
+      uses: actions/setup-node@v3
+      with:
+        node-version: "16.14.0"
 
       # Install all the dependencies
-      - name: Install dependencies
-        if: steps.appsmithctl_run_result.outputs.appsmithctl_run_result != 'success'
-        run: yarn install --frozen-lockfile
+    - name: Install dependencies
+      if: steps.appsmithctl_run_result.outputs.appsmithctl_run_result != 'success'
+      run: yarn install --frozen-lockfile
 
       # Run the Jest tests only if the workflow has been invoked in a PR
-      - name: Run the jest tests
-        if: steps.appsmithctl_run_result.outputs.appsmithctl_run_result != 'success'
-        run: yarn run test
+    - name: Run the jest tests
+      if: steps.appsmithctl_run_result.outputs.appsmithctl_run_result != 'success'
+      run: yarn run test
 
       # Set status = failure
-      - name: Set result as failed if there are build failures
-        if: failure()
-        run: |
-          echo "appsmithctl_run_result=failed" >> $GITHUB_OUTPUT > ~/appsmithctl_run_result
-          exit 1;
+    - name: Set result as failed if there are build failures
+      if: failure()
+      run: |
+        echo "appsmithctl_run_result=failed" >> $GITHUB_OUTPUT > ~/appsmithctl_run_result
+        exit 1;
 
-  
+
       # Set status = success
-      - name: Save the status of the run
-        run: echo "appsmithctl_run_result=success" >> $GITHUB_OUTPUT > ~/appsmithctl_run_result
+    - name: Save the status of the run
+      run: echo "appsmithctl_run_result=success" >> $GITHUB_OUTPUT > ~/appsmithctl_run_result
diff --git a/.github/workflows/integration-tests-command.yml b/.github/workflows/integration-tests-command.yml
--- a/.github/workflows/integration-tests-command.yml
+++ b/.github/workflows/integration-tests-command.yml
@@ -2,24 +2,23 @@ name: Appsmith External Integration Test Workflow
 
 on:
   # This workflow is only triggered by the ok to test command dispatch
-  repository_dispatch:
-    types: [ ok-to-test-command ]
+  workflow_dispatch: {}
 
 jobs:
   notify:
     runs-on: ubuntu-latest
     steps:
       # This step creates a comment on the PR with a link to this workflow run.
-      - name: Add a comment on the PR with link to workflow run
-        uses: peter-evans/create-or-update-comment@v2
-        with:
-          issue-number: ${{ github.event.client_payload.pull_request.number }}
-          body: |
-            Tests running at: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>.
-            Workflow: `${{ github.workflow }}`.
-            Commit: `${{ github.event.client_payload.slash_command.args.named.sha }}`.
-            PR: ${{ github.event.client_payload.pull_request.number }}.
-            Perf tests will be available at <https://app.appsmith.com/app/performance-infra-dashboard/pr-details-638dd7cd2913ba43778b915e?pr=${{ github.event.client_payload.pull_request.number }}&runId=${{ github.run_id }}_${{github.run_attempt}}>
+    - name: Add a comment on the PR with link to workflow run
+      uses: peter-evans/create-or-update-comment@v2
+      with:
+        issue-number: ${{ github.event.client_payload.pull_request.number }}
+        body: |
+          Tests running at: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>.
+          Workflow: `${{ github.workflow }}`.
+          Commit: `${{ github.event.client_payload.slash_command.args.named.sha }}`.
+          PR: ${{ github.event.client_payload.pull_request.number }}.
+          Perf tests will be available at <https://app.appsmith.com/app/performance-infra-dashboard/pr-details-638dd7cd2913ba43778b915e?pr=${{ github.event.client_payload.pull_request.number }}&runId=${{ github.run_id }}_${{github.run_attempt}}>
 
   server-build:
     name: server-build
@@ -57,7 +56,7 @@ jobs:
       pr: ${{ github.event.client_payload.pull_request.number }}
 
   ci-test:
-    needs: [ client-build, server-build, rts-build ]
+    needs: [client-build, server-build, rts-build]
     # Only run if the build step is successful
     if: success()
     name: ci-test
@@ -67,7 +66,7 @@ jobs:
       pr: ${{ github.event.client_payload.pull_request.number }}
 
   perf-test:
-    needs: [ client-build, server-build, rts-build ]
+    needs: [client-build, server-build, rts-build]
     # Only run if the build step is successful
     if: success()
     name: perf-test
@@ -77,7 +76,7 @@ jobs:
       pr: ${{ github.event.client_payload.pull_request.number }}
 
   ci-test-result:
-    needs: [ci-test, perf-test ]
+    needs: [ci-test, perf-test]
     # Only run if the ci-test with matrices step is successful
     if: always()
     runs-on: ubuntu-latest
@@ -85,143 +84,143 @@ jobs:
       run:
         shell: bash
     steps:
-      - name: Dump the client payload context
-        env:
-          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
-        run: echo "$PAYLOAD_CONTEXT"
+    - name: Dump the client payload context
+      env:
+        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
+      run: echo "$PAYLOAD_CONTEXT"
 
       # Download failed_spec list for all jobs
-      - uses: actions/download-artifact@v3
-        if: needs.ci-test.result
-        id: download_ci
-        with:
-          name: failed-spec-ci
-          path: ~/failed_spec_ci
+    - uses: actions/download-artifact@v3
+      if: needs.ci-test.result
+      id: download_ci
+      with:
+        name: failed-spec-ci
+        path: ~/failed_spec_ci
 
       # In case for any ci job failure, create combined failed spec
-      - name: "combine all specs for CI"
-        if: needs.ci-test.result != 'success'
-        run: cat ~/failed_spec_ci/failed_spec_ci* >> ~/combined_failed_spec_ci
+    - name: "combine all specs for CI"
+      if: needs.ci-test.result != 'success'
+      run: cat ~/failed_spec_ci/failed_spec_ci* >> ~/combined_failed_spec_ci
 
       # Force save the CI failed spec list into a cache
-      - name: Store the combined run result for CI
-        if: needs.ci-test.result != 'success'
-        uses: martijnhols/actions-cache/save@v3
-        with:
-          path: |
-            ~/combined_failed_spec_ci
-          key: ${{ github.run_id }}-"ci-test-result"
-          restore-keys: |
-            ${{ github.run_id }}-${{ github.job }}
+    - name: Store the combined run result for CI
+      if: needs.ci-test.result != 'success'
+      uses: martijnhols/actions-cache/save@v3
+      with:
+        path: |
+          ~/combined_failed_spec_ci
+        key: ${{ github.run_id }}-"ci-test-result"
+        restore-keys: |
+          ${{ github.run_id }}-${{ github.job }}
 
       # Upload combined failed CI spec list to a file
       # This is done for debugging.
-      - name: upload combined failed spec
-        if: needs.ci-test.result != 'success'
-        uses: actions/upload-artifact@v3
-        with:
-          name: combined_failed_spec_ci
-          path: ~/combined_failed_spec_ci
+    - name: upload combined failed spec
+      if: needs.ci-test.result != 'success'
+      uses: actions/upload-artifact@v3
+      with:
+        name: combined_failed_spec_ci
+        path: ~/combined_failed_spec_ci
 
-      - name: Get Latest flaky Tests
-        shell: bash
-        run: |
-          curl --request POST --url https://yatin-s-workspace-jk8ru5.us-east-1.xata.sh/db/CypressKnownFailures:main/tables/CypressKnownFailuires/query --header 'Authorization: Bearer ${{ secrets.XATA_TOKEN }}' --header 'Content-Type: application/json'|jq -r |grep Spec|cut -d ':' -f 2 2> /dev/null|sed 's/"//g'|sed 's/,//g' >  ~/knownfailures
+    - name: Get Latest flaky Tests
+      shell: bash
+      run: |
+        curl --request POST --url https://yatin-s-workspace-jk8ru5.us-east-1.xata.sh/db/CypressKnownFailures:main/tables/CypressKnownFailuires/query --header 'Authorization: Bearer ${{ secrets.XATA_TOKEN }}' --header 'Content-Type: application/json'|jq -r |grep Spec|cut -d ':' -f 2 2> /dev/null|sed 's/"//g'|sed 's/,//g' >  ~/knownfailures
 
      # Verify CI test failures against known failures
-      - name: Verify CI test failures against known failures
-        if: needs.ci-test.result != 'success'
-        shell: bash
-        run: |
-          new_failed_spec_env="<ol>$(comm -1 -3 <(sort ~/knownfailures) <(sort ~/combined_failed_spec_ci) | sed 's/|cypress|cypress/\n/g' | sed 's/^/<li>/')</ol>"
-          echo "$new_failed_spec_env"
-          echo "new_failed_spec_env<<EOF" >> $GITHUB_ENV
-          echo "$new_failed_spec_env" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
+    - name: Verify CI test failures against known failures
+      if: needs.ci-test.result != 'success'
+      shell: bash
+      run: |
+        new_failed_spec_env="<ol>$(comm -1 -3 <(sort ~/knownfailures) <(sort ~/combined_failed_spec_ci) | sed 's/|cypress|cypress/\n/g' | sed 's/^/<li>/')</ol>"
+        echo "$new_failed_spec_env"
+        echo "new_failed_spec_env<<EOF" >> $GITHUB_ENV
+        echo "$new_failed_spec_env" >> $GITHUB_ENV
+        echo "EOF" >> $GITHUB_ENV
 
-      - name: Add a comment on the PR with new CI failures
-        if: needs.ci-test.result != 'success'
-        uses: peter-evans/create-or-update-comment@v1
-        with:
-          issue-number: ${{ github.event.client_payload.pull_request.number }}
-          body: |
-            <details><summary>The following are new failures, please fix them before merging the PR</summary> ${{ env.new_failed_spec_env }}</details> 
+    - name: Add a comment on the PR with new CI failures
+      if: needs.ci-test.result != 'success'
+      uses: peter-evans/create-or-update-comment@v1
+      with:
+        issue-number: ${{ github.event.client_payload.pull_request.number }}
+        body: |
+          <details><summary>The following are new failures, please fix them before merging the PR</summary> ${{ env.new_failed_spec_env }}</details> 
 
       # Update check run called "ci-test-result"
-      - name: Mark ci-test-result job as complete
-        uses: actions/github-script@v6
-        id: update-check-run
-        if: ${{ always() }}
-        env:
-          run_id: ${{ github.run_id }}
-          repository: ${{ github.repository }}
-          number: ${{ github.event.client_payload.pull_request.number }}
-          job: ${{ github.job }}
+    - name: Mark ci-test-result job as complete
+      uses: actions/github-script@v6
+      id: update-check-run
+      if: ${{ always() }}
+      env:
+        run_id: ${{ github.run_id }}
+        repository: ${{ github.repository }}
+        number: ${{ github.event.client_payload.pull_request.number }}
+        job: ${{ github.job }}
           # Conveniently, job.status maps to https://developer.github.com/v3/checks/runs/#update-a-check-run
-          conclusion: ${{ job.status }}
-          matrix_result: ${{ toJson(needs.ci-test) }}
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const { data: pull } = await github.rest.pulls.get({
-              ...context.repo,
-              pull_number: process.env.number
+        conclusion: ${{ job.status }}
+        matrix_result: ${{ toJson(needs.ci-test) }}
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          const { data: pull } = await github.rest.pulls.get({
+            ...context.repo,
+            pull_number: process.env.number
+          });
+          const ref = pull.head.sha;
+
+          const { data: checks } = await github.rest.checks.listForRef({
+            ...context.repo,
+            ref
+          });
+
+          const check = checks.check_runs.filter(c => c.name === process.env.job);
+
+          if(check.length == 0) {
+            const head_sha = pull.head.sha;
+            const { data: completed_at } = await github.rest.checks.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              head_sha: head_sha,
+              name: process.env.job,
+              status: 'completed',
+              conclusion: JSON.parse(process.env.matrix_result).result,
+              output: {
+                title: "Integration tests result for ok to test",
+                summary: "https://github.com/" + process.env.repository + "/actions/runs/" + process.env.run_id
+              }
             });
-            const ref = pull.head.sha;
 
-            const { data: checks } = await github.rest.checks.listForRef({
-              ...context.repo,
-              ref
-            });
-
-            const check = checks.check_runs.filter(c => c.name === process.env.job);
-
-            if(check.length == 0) {
-              const head_sha = pull.head.sha;
-              const { data: completed_at } = await github.rest.checks.create({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                head_sha: head_sha,
-                name: process.env.job,
+            return completed_at;
+          } else {
+            try {
+              const { data: result } = await github.rest.checks.update({
+                ...context.repo,
+                check_run_id: check[0].id,
                 status: 'completed',
                 conclusion: JSON.parse(process.env.matrix_result).result,
-                output: {
-                  title: "Integration tests result for ok to test",
-                  summary: "https://github.com/" + process.env.repository + "/actions/runs/" + process.env.run_id
-                }
+                  output: {
+                    title: "Integration tests result for ok to test",
+                    summary: "https://github.com/" + process.env.repository + "/actions/runs/" + process.env.run_id
+                  }
               });
-
-              return completed_at;
-            } else {
-              try {
-                const { data: result } = await github.rest.checks.update({
-                  ...context.repo,
-                  check_run_id: check[0].id,
-                  status: 'completed',
-                  conclusion: JSON.parse(process.env.matrix_result).result,
-                    output: {
-                      title: "Integration tests result for ok to test",
-                      summary: "https://github.com/" + process.env.repository + "/actions/runs/" + process.env.run_id
-                    }
-                });
-                console.log({ result });
-                return result;
-              } catch(e) {
-                console.error({ error: e.message });
-              }
+              console.log({ result });
+              return result;
+            } catch(e) {
+              console.error({ error: e.message });
             }
+          }
 
-      - name: Dump the client payload context
-        env:
-          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
-        run: echo "$PAYLOAD_CONTEXT"
+    - name: Dump the client payload context
+      env:
+        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
+      run: echo "$PAYLOAD_CONTEXT"
 
-      - name: Check ci-test set status
-        if: needs.ci-test.result != 'success' || needs.perf-test.result != 'success'
-        run: exit 1
+    - name: Check ci-test set status
+      if: needs.ci-test.result != 'success' || needs.perf-test.result != 'success'
+      run: exit 1
 
   package:
-    needs: [ ci-test ]
+    needs: [ci-test]
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -231,60 +230,60 @@ jobs:
 
     steps:
       # Update check run called "package"
-      - name: Mark package job as complete
-        uses: actions/github-script@v6
-        id: update-check-run
-        if: ${{ always() }}
-        env:
-          run_id: ${{ github.run_id }}
-          repository: ${{ github.repository }}
-          number: ${{ github.event.client_payload.pull_request.number }}
-          job: ${{ github.job }}
+    - name: Mark package job as complete
+      uses: actions/github-script@v6
+      id: update-check-run
+      if: ${{ always() }}
+      env:
+        run_id: ${{ github.run_id }}
+        repository: ${{ github.repository }}
+        number: ${{ github.event.client_payload.pull_request.number }}
+        job: ${{ github.job }}
           # Conveniently, job.status maps to https://developer.github.com/v3/checks/runs/#update-a-check-run
-          conclusion: ${{ job.status }}
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const { data: pull } = await github.rest.pulls.get({
-              ...context.repo,
-              pull_number: process.env.number
-            });
-            const ref = pull.head.sha;
+        conclusion: ${{ job.status }}
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          const { data: pull } = await github.rest.pulls.get({
+            ...context.repo,
+            pull_number: process.env.number
+          });
+          const ref = pull.head.sha;
 
-            const { data: checks } = await github.rest.checks.listForRef({
-              ...context.repo,
-              ref
-            });
+          const { data: checks } = await github.rest.checks.listForRef({
+            ...context.repo,
+            ref
+          });
 
-            const check = checks.check_runs.filter(c => c.name === process.env.job);
+          const check = checks.check_runs.filter(c => c.name === process.env.job);
 
-            if(check.length == 0) {
-              const head_sha = pull.head.sha;
-              const { data: completed_at } = await github.rest.checks.create({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                head_sha: head_sha,
-                name: process.env.job,
-                status: 'completed',
-                conclusion: process.env.conclusion,
-                output: {
-                  title: "Package result for ok to test",
-                  summary: "https://github.com/" + process.env.repository + "/actions/runs/" + process.env.run_id
-                }
-              });
-
-              return completed_at;
-            } else {
-              const { data: result } = await github.rest.checks.update({
-              ...context.repo,
-              check_run_id: check[0].id,
+          if(check.length == 0) {
+            const head_sha = pull.head.sha;
+            const { data: completed_at } = await github.rest.checks.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              head_sha: head_sha,
+              name: process.env.job,
               status: 'completed',
               conclusion: process.env.conclusion,
-                output: {
-                  title: "Package result for ok to test",
-                  summary: "https://github.com/" + process.env.repository + "/actions/runs/" + process.env.run_id
-                }
+              output: {
+                title: "Package result for ok to test",
+                summary: "https://github.com/" + process.env.repository + "/actions/runs/" + process.env.run_id
+              }
             });
 
-            return result;
-            }
+            return completed_at;
+          } else {
+            const { data: result } = await github.rest.checks.update({
+            ...context.repo,
+            check_run_id: check[0].id,
+            status: 'completed',
+            conclusion: process.env.conclusion,
+              output: {
+                title: "Package result for ok to test",
+                summary: "https://github.com/" + process.env.repository + "/actions/runs/" + process.env.run_id
+              }
+          });
+
+          return result;
+          }
diff --git a/.github/workflows/test-build-docker-image.yml b/.github/workflows/test-build-docker-image.yml
--- a/.github/workflows/test-build-docker-image.yml
+++ b/.github/workflows/test-build-docker-image.yml
@@ -2,17 +2,7 @@ name: Test, build and push Docker Image
 
 on:
   # This line enables manual triggering of this workflow.
-  workflow_dispatch:
-
-  # trigger for pushes to release and master
-  push:
-    branches: [release, master]
-    paths:
-      - "app/client/**"
-      - "app/server/**"
-      - "app/rts/**"
-      - "!app/client/cypress/manual_TestSuite/**"
-
+  workflow_dispatch: {}
 jobs:
 
   server-build:
@@ -47,7 +37,7 @@ jobs:
       pr: 0
 
   ci-test:
-    needs: [ client-build, server-build, rts-build ]
+    needs: [client-build, server-build, rts-build]
     # Only run if the build step is successful
     if: success()
     name: ci-test
@@ -58,64 +48,61 @@ jobs:
 
   ci-test-result:
     needs: [ci-test]
-    if: always() &&
-      (github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'push' ||
-      (github.event_name == 'pull_request_review' &&
-      github.event.review.state == 'approved' &&
-      github.event.pull_request.head.repo.full_name == github.repository))
+    if: always() && (github.event_name == 'workflow_dispatch' || github.event_name
+      == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state
+      == 'approved' && github.event.pull_request.head.repo.full_name == github.repository))
     runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
     steps:
-      - run: echo "All ci-test matrices completed"
+    - run: echo "All ci-test matrices completed"
 
       # Download failed_spec_ci list for all CI container jobs
-      - uses: actions/download-artifact@v3
-        if: needs.ci-test.result
-        id: download_ci
-        with:
-          name: failed-spec-ci
-          path: ~/failed_spec_ci
+    - uses: actions/download-artifact@v3
+      if: needs.ci-test.result
+      id: download_ci
+      with:
+        name: failed-spec-ci
+        path: ~/failed_spec_ci
 
       # In case for any ci job failure, create combined failed spec
-      - name: "combine all specs for CI"
-        if: needs.ci-test.result != 'success'
-        run: cat ~/failed_spec_ci/failed_spec_ci* >> ~/combined_failed_spec_ci
+    - name: "combine all specs for CI"
+      if: needs.ci-test.result != 'success'
+      run: cat ~/failed_spec_ci/failed_spec_ci* >> ~/combined_failed_spec_ci
 
       # Force save the CI failed spec list into a cache
-      - name: Store the combined run result for CI
-        if: needs.ci-test.result != 'success'
-        uses: martijnhols/actions-cache/save@v3
-        with:
-          path: |
-            ~/combined_failed_spec_ci
-          key: ${{ github.run_id }}-"ci-test-result"
-          restore-keys: |
-            ${{ github.run_id }}-${{ github.job }}
+    - name: Store the combined run result for CI
+      if: needs.ci-test.result != 'success'
+      uses: martijnhols/actions-cache/save@v3
+      with:
+        path: |
+          ~/combined_failed_spec_ci
+        key: ${{ github.run_id }}-"ci-test-result"
+        restore-keys: |
+          ${{ github.run_id }}-${{ github.job }}
 
       # Upload combined failed CI spec list to a file
       # This is done for debugging.
-      - name: upload combined failed spec
-        if: needs.ci-test.result != 'success'
-        uses: actions/upload-artifact@v3
-        with:
-          name: combined_failed_spec_ci
-          path: ~/combined_failed_spec_ci
+    - name: upload combined failed spec
+      if: needs.ci-test.result != 'success'
+      uses: actions/upload-artifact@v3
+      with:
+        name: combined_failed_spec_ci
+        path: ~/combined_failed_spec_ci
 
-      - name: Return status for ui-matrix
-        run: |
-          if [[ "${{ needs.ci-test.result }}" == "success" ]]; then
-            echo "Integration tests completed successfully!";
-            exit 0;
-          elif [[ "${{ needs.ci-test.result }}" == "skipped" ]]; then
-            echo "Integration tests were skipped";
-            exit 1;
-          else
-            echo "Integration tests have failed";
-            exit 1;
-          fi
+    - name: Return status for ui-matrix
+      run: |
+        if [[ "${{ needs.ci-test.result }}" == "success" ]]; then
+          echo "Integration tests completed successfully!";
+          exit 0;
+        elif [[ "${{ needs.ci-test.result }}" == "skipped" ]]; then
+          echo "Integration tests were skipped";
+          exit 1;
+        else
+          echo "Integration tests have failed";
+          exit 1;
+        fi
 
   package:
     needs: ci-test
@@ -126,114 +113,109 @@ jobs:
       id-token: write
 
     # Run this job irrespective of tests failing, if this is the release branch; or only if the tests pass, if this is the master branch.
-    if: (success() && github.ref == 'refs/heads/master') ||
-      ( always() &&
-      (
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'push' ||
-      (
-      github.event_name == 'pull_request_review' &&
-      github.event.review.state == 'approved' &&
-      github.event.pull_request.head.repo.full_name == github.repository
-      )
-      ) &&
-      github.ref == 'refs/heads/release'
-      )
+    if: (success() && github.ref == 'refs/heads/master') || ( always() && ( github.event_name
+      == 'workflow_dispatch' || github.event_name == 'push' || ( github.event_name
+      == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.head.repo.full_name
+      == github.repository ) ) && github.ref == 'refs/heads/release' )
 
     steps:
       # Checkout the code
-      - name: Checkout the merged commit from PR and base branch
-        if: github.event_name == 'pull_request_review'
-        uses: actions/checkout@v3
-        with:
-          ref: refs/pull/${{ github.event.pull_request.number }}/merge
+    - name: Checkout the merged commit from PR and base branch
+      if: github.event_name == 'pull_request_review'
+      uses: actions/checkout@v3
+      with:
+        ref: refs/pull/${{ github.event.pull_request.number }}/merge
 
-      - name: Checkout the head commit of the branch
-        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
-        uses: actions/checkout@v3
+    - name: Checkout the head commit of the branch
+      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
+      uses: actions/checkout@v3
 
-      - name: Download the react build artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: client-build
-          path: app/client/build
+    - name: Download the react build artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: client-build
+        path: app/client/build
 
-      - name: Download the server build artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: server-build
-          path: app/server/dist
+    - name: Download the server build artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: server-build
+        path: app/server/dist
 
-      - name: Download the rts build artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: rts-dist
-          path: app/rts/dist
+    - name: Download the rts build artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: rts-dist
+        path: app/rts/dist
 
-      - name: Untar the rts folder
-        run: |
-          tar -xvf app/rts/dist/rts-dist.tar -C app/rts/
-          echo "Cleaning up the tar files"
-          rm app/rts/dist/rts-dist.tar
+    - name: Untar the rts folder
+      run: |
+        tar -xvf app/rts/dist/rts-dist.tar -C app/rts/
+        echo "Cleaning up the tar files"
+        rm app/rts/dist/rts-dist.tar
 
       # Here, the GITHUB_REF is of type /refs/head/<branch_name>. We extract branch_name from this by removing the
       # first 11 characters. This can be used to build images for several branches
-      - name: Get the version to tag the Docker image
-        id: vars
-        run: echo tag=$(echo ${GITHUB_REF:11}) >> $GITHUB_OUTPUT
+    - name: Get the version to tag the Docker image
+      id: vars
+      run: echo tag=$(echo ${GITHUB_REF:11}) >> $GITHUB_OUTPUT
 
-      - name: Set up Depot CLI
-        uses: depot/setup-action@v1
+    - name: Set up Depot CLI
+      uses: depot/setup-action@v1
 
-      - name: Login to DockerHub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+    - name: Login to DockerHub
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.DOCKER_HUB_USERNAME }}
+        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
       # Build release Docker image and push to Docker Hub
-      - name: Push client release image to Docker Hub
-        if: success() && github.ref == 'refs/heads/release' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
-        uses: depot/build-push-action@v1
-        with:
-          context: app/client
-          push: true
-          tags: |
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:${{steps.vars.outputs.tag}}
+    - name: Push client release image to Docker Hub
+      if: success() && github.ref == 'refs/heads/release' && (github.event_name ==
+        'push' || github.event_name == 'workflow_dispatch')
+      uses: depot/build-push-action@v1
+      with:
+        context: app/client
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:${{steps.vars.outputs.tag}}
 
       # Build master Docker image and push to Docker Hub
-      - name: Push client master image to Docker Hub with commit tag
-        if: success() && github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
-        uses: depot/build-push-action@v1
-        with:
-          context: app/client
-          push: true
-          tags: |
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:${{ github.sha }}
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:nightly
+    - name: Push client master image to Docker Hub with commit tag
+      if: success() && github.ref == 'refs/heads/master' && (github.event_name ==
+        'push' || github.event_name == 'workflow_dispatch')
+      uses: depot/build-push-action@v1
+      with:
+        context: app/client
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:${{ github.sha }}
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:nightly
 
-      - name: Build and push release image to Docker Hub
-        if: success() && github.ref == 'refs/heads/release' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
-        uses: depot/build-push-action@v1
-        with:
-          context: .
-          push: true
-          platforms: linux/arm64,linux/amd64
-          tags: |
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:${{steps.vars.outputs.tag}}
+    - name: Build and push release image to Docker Hub
+      if: success() && github.ref == 'refs/heads/release' && (github.event_name ==
+        'push' || github.event_name == 'workflow_dispatch')
+      uses: depot/build-push-action@v1
+      with:
+        context: .
+        push: true
+        platforms: linux/arm64,linux/amd64
+        tags: |
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:${{steps.vars.outputs.tag}}
 
-      - name: Build and push master image to Docker Hub with commit tag
-        if: success() && github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
-        uses: depot/build-push-action@v1
-        with:
-          context: .
-          push: true
-          platforms: linux/arm64,linux/amd64
-          build-args: |
-            APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }}
-          tags: |
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:${{ github.sha }}
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:nightly
+    - name: Build and push master image to Docker Hub with commit tag
+      if: success() && github.ref == 'refs/heads/master' && (github.event_name ==
+        'push' || github.event_name == 'workflow_dispatch')
+      uses: depot/build-push-action@v1
+      with:
+        context: .
+        push: true
+        platforms: linux/arm64,linux/amd64
+        build-args: |
+          APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }}
+        tags: |
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:${{ github.sha }}
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:nightly
 
       # - name: Check and push CI image to Docker Hub with commit tag
       #   if: success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
@@ -258,44 +240,44 @@ jobs:
       #     fi
 
       # Build release Docker image and push to Docker Hub
-      - name: Push server release image to Docker Hub
-        if: success() && github.ref == 'refs/heads/release'
-        uses: depot/build-push-action@v1
-        with:
-          context: app/server
-          push: true
-          tags: |
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:${{steps.vars.outputs.tag}}
+    - name: Push server release image to Docker Hub
+      if: success() && github.ref == 'refs/heads/release'
+      uses: depot/build-push-action@v1
+      with:
+        context: app/server
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:${{steps.vars.outputs.tag}}
 
       # Build master Docker image and push to Docker Hub
-      - name: Push server master image to Docker Hub with commit tag
-        if: success() && github.ref == 'refs/heads/master'
-        uses: depot/build-push-action@v1
-        with:
-          context: app/server
-          push: true
-          build-args: |
-            APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }}
-          tags: |
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:${{ github.sha }}
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:nightly
+    - name: Push server master image to Docker Hub with commit tag
+      if: success() && github.ref == 'refs/heads/master'
+      uses: depot/build-push-action@v1
+      with:
+        context: app/server
+        push: true
+        build-args: |
+          APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }}
+        tags: |
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:${{ github.sha }}
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:nightly
       # Build release Docker image and push to Docker Hub
-      - name: Push RTS release image to Docker Hub
-        if: success() && github.ref == 'refs/heads/release'
-        uses: depot/build-push-action@v1
-        with:
-          context: app/rts
-          push: true
-          tags: |
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-rts:${{steps.vars.outputs.tag}}
+    - name: Push RTS release image to Docker Hub
+      if: success() && github.ref == 'refs/heads/release'
+      uses: depot/build-push-action@v1
+      with:
+        context: app/rts
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-rts:${{steps.vars.outputs.tag}}
 
       # Build master Docker image and push to Docker Hub
-      - name: Push RTS master image to Docker Hub with commit tag
-        if: success() && github.ref == 'refs/heads/master'
-        uses: depot/build-push-action@v1
-        with:
-          context: app/rts
-          push: true
-          tags: |
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-rts:${{ github.sha }}
-            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-rts:nightly
+    - name: Push RTS master image to Docker Hub with commit tag
+      if: success() && github.ref == 'refs/heads/master'
+      uses: depot/build-push-action@v1
+      with:
+        context: app/rts
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-rts:${{ github.sha }}
+          ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-rts:nightly
